before_install:
  - git clone https://github.com/G2Jose/personal-website.git

install:
  - yarn
  - cd personal-website
  - yarn
  - cd ..

script:
  - npm run lint
  - CI="" npm run build
  - rm -rf personal-website/public/projects/livetransit/*
  - mv build/* personal-website/public/projects/livetransit/
  - cd personal-website

after_success:
  - npm install -g firebase-tools
  - firebase deploy